title: Home
author:
  name: busracagliyan
  # github: https://github.com/busracagliyan
  # linkedin: https://www.linkedin.com/in/busracagliyan

# description: >
#   test

theme: minima

plugins:
  - jekyll-feed
  # - jekyll-seo-tag

header_pages:
  - projects.md
  - about.md

minima:
  date_format: "%b %d, %Y"

minima:
  skin: auto

collections:
  projects:
    output: true

social_links:
 - { platform: linkedin,  user_url: "https://www.linkedin.com/in/busracagliyan"}
 - { platform: github,    user_url: "https://github.com/busracagliyan"}
